// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-players.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_players_default = defineTool({
  name: "list_players",
  title: "List players",
  description: "List scouted players belonging to the signed-in user. Supports optional filters by position, nationality, and current club, and a result limit.",
  inputSchema: {
    position: z.string().optional().describe("Filter by exact position (e.g. striker, winger, centre_back)."),
    nationality: z.string().optional().describe("Filter by nationality."),
    current_club: z.string().optional().describe("Filter by current club (partial match)."),
    limit: z.number().int().min(1).max(200).optional().describe("Maximum number of players to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ position, nationality, current_club, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("players").select("id, full_name, position, nationality, current_club, date_of_birth, preferred_foot, height_cm").order("full_name", { ascending: true }).limit(limit ?? 50);
    if (position) q = q.eq("position", position);
    if (nationality) q = q.eq("nationality", nationality);
    if (current_club) q = q.ilike("current_club", `%${current_club}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { players: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-player.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_player_default = defineTool2({
  name: "get_player",
  title: "Get player",
  description: "Get the full profile of a single scouted player (owned by the signed-in user) by id, including all scouting reports.",
  inputSchema: {
    player_id: z2.string().uuid().describe("UUID of the player.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ player_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data: player, error: pErr } = await supabase.from("players").select("*").eq("id", player_id).maybeSingle();
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    if (!player) return { content: [{ type: "text", text: "Player not found" }], isError: true };
    const { data: reports } = await supabase.from("scouting_reports").select("*").eq("player_id", player_id).order("created_at", { ascending: false });
    const payload = { player, reports: reports ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-reports.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_reports_default = defineTool3({
  name: "list_reports",
  title: "List scouting reports",
  description: "List scouting reports for the signed-in user. Optionally filter by player_id and limit the count.",
  inputSchema: {
    player_id: z3.string().uuid().optional().describe("Filter reports to a specific player."),
    limit: z3.number().int().min(1).max(200).optional().describe("Maximum number of reports to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ player_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("scouting_reports").select("*").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (player_id) q = q.eq("player_id", player_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { reports: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-players.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_players_default = defineTool4({
  name: "search_players",
  title: "Search players",
  description: "Free-text search across the signed-in user's players by name, club, or nationality.",
  inputSchema: {
    query: z4.string().min(1).describe("Text to search across full_name, current_club, and nationality."),
    limit: z4.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const like = `%${query}%`;
    const { data, error } = await supabaseForUser4(ctx).from("players").select("id, full_name, position, nationality, current_club, date_of_birth").or(`full_name.ilike.${like},current_club.ilike.${like},nationality.ilike.${like}`).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { players: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "uhzrwimvyjwhzhgybgsu";
var mcp_default = defineMcp({
  name: "the-football-scout-mcp",
  title: "The Football Scout",
  version: "0.1.0",
  instructions: "Tools for The Football Scout. Use search_players / list_players to find players in the signed-in scout's database, get_player for full detail with all scouting reports, and list_reports to browse reports.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_players_default, get_player_default, list_reports_default, search_players_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
